name: nutrismart
description: "NutriSmart - Aplikasi untuk meningkatkan nutrisi anak sekolah"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.7.16

  # State Management
  get: ^4.6.6

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.19.0

  # Face Recognition
  google_mlkit_face_detection: ^0.9.0
  camera: ^0.10.5+9

  # Others
  shared_preferences: ^2.2.2
  http: ^1.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  flutter_local_notifications: ^16.3.2
  device_info_plus: ^9.1.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
